// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: exercise_query.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createExercise = `-- name: CreateExercise :exec
INSERT INTO exercises (id_exercise, name_exercise, description, uri_gif) 
VALUES ($1,$2,$3,$4)
RETURNING id_exercise, name_exercise, description, uri_gif
`

type CreateExerciseParams struct {
	IDExercise   uuid.UUID
	NameExercise string
	Description  string
	UriGif       string
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) error {
	_, err := q.db.ExecContext(ctx, createExercise,
		arg.IDExercise,
		arg.NameExercise,
		arg.Description,
		arg.UriGif,
	)
	return err
}

const createMuscleGroupExercises = `-- name: CreateMuscleGroupExercises :exec
INSERT INTO muscle_group_exercises (id_exercise, muscle_group) 
VALUES ($1,$2)
RETURNING id_exercise, muscle_group
`

type CreateMuscleGroupExercisesParams struct {
	IDExercise  uuid.UUID
	MuscleGroup string
}

func (q *Queries) CreateMuscleGroupExercises(ctx context.Context, arg CreateMuscleGroupExercisesParams) error {
	_, err := q.db.ExecContext(ctx, createMuscleGroupExercises, arg.IDExercise, arg.MuscleGroup)
	return err
}
