// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package database

import (
	"database/sql"
)

type User struct {
	IDUser         string
	FullName       string
	Email          string
	ProfilePicture sql.NullString
}
