// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package sqlc

import (
	"database/sql"

	"github.com/google/uuid"
)

type User struct {
	IDUser         uuid.UUID
	FullName       string
	Email          string
	ProfilePicture sql.NullString
}
