version: "3"

services:
  postgres:
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_USER: "renato"
      POSTGRES_PASSWORD: "renato"
      POSTGRES_DB: "customer"
      TZ: "America/Sao_Paulo"
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "reangeline@hotmail.com"
      PGADMIN_DEFAULT_PASSWORD: "renato"
    ports:
      - "54321:80"
    depends_on:
      - postgres
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
